const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://opensource-demo.orangehrmlive.com/');
  await page.getByPlaceholder('Username').fill('Admin');
  await page.getByPlaceholder('Password').fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('option', { name: 'Admin' }).click();
  const employeeNameInput = page.getByPlaceholder('Type for hints...');
  await employeeNameInput.fill('Ranga');
  await page.locator('.oxd-autocomplete-option').filter({ hasText: 'Ranga' }).first().click();
  await page.locator('.oxd-select-text').nth(1).click();
  await page.getByRole('option', { name: 'Enabled' }).click();
  await page.locator('.oxd-form').locator('input').nth(1).fill('avantika.auto.user99');
  await page.locator('.oxd-form').locator('input[type="password"]').first().fill('Test@12345Aa!');
  await page.locator('.oxd-form').locator('input[type="password"]').nth(1).fill('Test@12345Aa!');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.waitForTimeout(3000);
  await page.locator('.oxd-form').locator('input').first().fill('avantika.auto.user99');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.waitForTimeout(3000);
  const contents = await page.locator('.oxd-table').innerHTML();
  console.log('TABLE HTML:\n', contents);
  const texts = await page.locator('text=No Records Found').allTextContents();
  console.log('TEXTS: ', texts);
  const spans = await page.locator('span:has-text("No Records Found")').evaluateAll(nodes => nodes.map(n => ({outerHTML:n.outerHTML, className:n.className, text:n.textContent}))); 
  console.log('SPANs:', JSON.stringify(spans, null, 2));
  const ps = await page.locator('p:has-text("No Records Found")').evaluateAll(nodes => nodes.map(n => ({outerHTML:n.outerHTML, className:n.className, text:n.textContent}))); 
  console.log('PARAs:', JSON.stringify(ps, null, 2));
  await browser.close();
})();